# Generated by Django 4.2.20 on 2025-03-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('parachutists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Активна'), ('Completed', 'Завершена'), ('Archived', 'В архиве')], default='Active', max_length=50)),
                ('instructor', models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor')),
            ],
            options={
                'db_table': 'training_group',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingGroupParachutist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theory_passed', models.BooleanField(default=False)),
                ('practice_passed', models.BooleanField(default=False)),
                ('certificate_check', models.BooleanField(default=False)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='training_groups.traininggroup')),
                ('parachutist', models.ForeignKey(db_column='parachutist_id', on_delete=django.db.models.deletion.CASCADE, to='parachutists.parachutist')),
            ],
            options={
                'db_table': 'training_group_parachutist',
                'unique_together': {('group', 'parachutist')},
            },
        ),
    ]
