# Generated by Django 4.2.20 on 2025-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parachutists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В процессе'), ('closed', 'Закрыта')], default='open', max_length=20)),
                ('parachutists', models.ManyToManyField(blank=True, related_name='training_groups', to='parachutists.parachutist')),
            ],
        ),
    ]
