# Generated by Django 4.2.20 on 2025-03-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parachutists', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumpGroup',
            fields=[
                ('jump_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('jump_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('altitude', models.PositiveIntegerField(help_text='Высота в метрах')),
                ('status', models.CharField(choices=[('Planned', 'Запланирован'), ('Completed', 'Завершен'), ('Cancelled', 'Отменен')], default='Planned', max_length=50)),
                ('instructor', models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor')),
            ],
            options={
                'db_table': 'jump_group',
                'ordering': ['-jump_date'],
            },
        ),
        migrations.CreateModel(
            name='JumpRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_status', models.CharField(choices=[('Pending', 'Ожидает'), ('Approved', 'Одобрена'), ('Denied', 'Отклонена')], default='Pending', max_length=50)),
                ('result_status', models.CharField(blank=True, choices=[('Success', 'Успешно'), ('Failed', 'Неудачно'), ('Cancelled', 'Отменен')], max_length=50, null=True)),
                ('jump_result', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('jump_group', models.ForeignKey(db_column='jump_group_id', on_delete=django.db.models.deletion.CASCADE, to='jumps.jumpgroup')),
                ('parachutist', models.ForeignKey(db_column='parachutist_id', on_delete=django.db.models.deletion.CASCADE, to='parachutists.parachutist')),
            ],
            options={
                'db_table': 'jump_request',
                'ordering': ['-requested_at'],
            },
        ),
    ]
