# Generated by Django 4.2.20 on 2025-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
