# Generated by Django 4.2.20 on 2025-03-30 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parachutist',
            fields=[
                ('parachutist_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('refusal_reason', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parachutist',
            },
        ),
        migrations.CreateModel(
            name='ParachutistStatusHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('parachutist', models.ForeignKey(db_column='parachutist_id', on_delete=django.db.models.deletion.CASCADE, to='parachutists.parachutist')),
            ],
            options={
                'db_table': 'parachutist_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
