# Generated by Django 4.2.20 on 2025-03-30 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(choices=[('AFF', 'AFF-инструктор'), ('Tandem', 'Тандем-инструктор'), ('PDP', 'ПДП-инструктор')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Активен'), ('Inactive', 'Неактивен'), ('Vacation', 'В отпуске')], default='Active', max_length=50)),
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
    ]
