# Generated by Django 4.2.20 on 2025-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_jumpassignment_completed_jumpassignment_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traininggroupparachutist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='traininggroupparachutist',
            name='exam_passed',
            field=models.BooleanField(default=False),
        ),
    ]
