# Generated by Django 4.2.20 on 2025-04-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_alter_traininggroupparachutist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prejumpcheck',
            name='parachutist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='instructors.parachutist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='created', max_length=20),
        ),
    ]
