# Generated by Django 4.2.20 on 2025-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_prejumpcheck_parachutist_alter_traininggroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroupparachutist',
            name='ready_for_jump',
            field=models.BooleanField(default=False),
        ),
    ]
