# Generated by Django 4.2.20 on 2025-04-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_jumpgroup_end_date_time_jumpgroup_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumpgroup',
            name='status',
            field=models.CharField(choices=[('Created', 'Создана'), ('Pre-Flight Preparation', 'Предполетная подготовка'), ('Jump In Progress', 'Прыжок в процессе'), ('Completed', 'Завершена'), ('Cancelled', 'Отменена')], default='Created', max_length=50),
        ),
    ]
