# Generated by Django 4.2.20 on 2025-04-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0007_alter_jumpgroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prejumpcheck',
            name='correct_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
