# Generated by Django 4.2.20 on 2025-04-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0008_prejumpcheck_correct_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumpGroupParachutist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('Pending', 'Ожидает'), ('Approved', 'Одобрена'), ('Denied', 'Отклонена')], default='Pending', max_length=50)),
                ('theory_passed', models.BooleanField(default=False)),
                ('practice_passed', models.BooleanField(default=False)),
                ('medical_certified', models.BooleanField(default=False)),
                ('equipment_checked', models.BooleanField(default=False)),
                ('correct_assignment', models.BooleanField(default=False)),
                ('jump_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.jumpgroup')),
                ('parachutist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.parachutist')),
            ],
        ),
        migrations.RemoveField(
            model_name='prejumpcheck',
            name='jump_group',
        ),
        migrations.RemoveField(
            model_name='prejumpcheck',
            name='parachutist',
        ),
        migrations.DeleteModel(
            name='JumpRequest',
        ),
        migrations.DeleteModel(
            name='PreJumpCheck',
        ),
    ]
