# Generated by Django 4.2.20 on 2025-05-12 20:22

from django.db import migrations


def add_instructors(apps, schema_editor):
    Instructor = apps.get_model('instructors', 'Instructor')

    # Создание тестовых данных
    instructors = [
        Instructor(
            first_name="Иван",
            middle_name="Александрович",
            last_name="Петров",
            contact_info="ivan.petrov@example.com",
            qualification="Мастер спорта",
            status="Активен"
        ),
        Instructor(
            first_name="Мария",
            middle_name="Викторовна",
            last_name="Сидорова",
            contact_info="maria.sidorova@example.com",
            qualification="Инструктор первой категории",
            status="Активен"
        ),
        Instructor(
            first_name="Дмитрий",
            middle_name="Сергеевич",
            last_name="Козлов",
            contact_info="dmitry.kozlova@example.com",
            qualification="Кандидат в мастера спорта",
            status="На обучении"
        ),
        Instructor(
            first_name="Елена",
            middle_name="Ивановна",
            last_name="Горшкова",
            contact_info="elena.gorshkova@example.com",
            qualification="Инструктор высшей категории",
            status="Активен"
        ),
        Instructor(
            first_name="Алексей",
            middle_name="Петрович",
            last_name="Михайлов",
            contact_info="aleksey.mikhailov@example.com",
            qualification="Мастер спорта международного класса",
            status="Активен"
        ),
    ]

    # Сохранение данных в базе
    for instructor in instructors:
        instructor.save()


def remove_instructors(apps, schema_editor):
    Instructor = apps.get_model('instructors', 'Instructor')
    Instructor.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('instructors', '0009_jumpgroupparachutist_remove_prejumpcheck_jump_group_and_more'),
        # Замените на вашу последнюю миграцию
    ]

    operations = [
        migrations.RunPython(add_instructors, remove_instructors),
    ]
