# Generated by Django 4.2.20 on 2025-05-12 20:35

from django.db import migrations


def add_parachutists(apps, schema_editor):
    Parachutist = apps.get_model('instructors', 'Parachutist')

    # Создание тестовых данных
    parachutists = [
        Parachutist(
            first_name="Александр",
            middle_name="Васильевич",
            last_name="Иванов",
            contact_info="alexandr.ivanov@example.com"
        ),
        Parachutist(
            first_name="Ольга",
            middle_name="Николаевна",
            last_name="Петрова",
            contact_info="olga.petrova@example.com"
        ),
        Parachutist(
            first_name="Игорь",
            middle_name="Юрьевич",
            last_name="Смирнов",
            contact_info="igor.smirnov@example.com"
        ),
        Parachutist(
            first_name="Наталья",
            middle_name="Александровна",
            last_name="Кузнецова",
            contact_info="natalia.kuznetsova@example.com"
        ),
        Parachutist(
            first_name="Максим",
            middle_name="Петрович",
            last_name="Лебедев",
            contact_info="maxim.lebedev@example.com"
        ),
    ]

    # Сохранение данных в базе
    for parachutist in parachutists:
        parachutist.save()


def remove_parachutists(apps, schema_editor):
    Parachutist = apps.get_model('instructors', 'Parachutist')
    Parachutist.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('instructors', '0010_add_instructors'),
        # Замените на вашу последнюю миграцию
    ]

    operations = [
        migrations.RunPython(add_parachutists, remove_parachutists),
    ]
