# Generated by Django 4.2.20 on 2025-05-12

from django.db import migrations
from django.utils import timezone


def create_training_groups(apps, schema_editor):
    # Получаем модели
    Instructor = apps.get_model('instructors', 'Instructor')
    TrainingGroup = apps.get_model('instructors', 'TrainingGroup')

    # Получаем инструкторов
    instructor_1 = Instructor.objects.get(instructor_id=1)
    instructor_2 = Instructor.objects.get(instructor_id=2)

    # Создаем две учебные группы
    TrainingGroup.objects.create(
        instructor=instructor_1,
        group_name="Группа 1",
        start_date_time=timezone.now(),
        end_date_time=timezone.now() + timezone.timedelta(hours=2),
        status="created"
    )

    TrainingGroup.objects.create(
        instructor=instructor_2,
        group_name="Группа 2",
        start_date_time=timezone.now(),
        end_date_time=timezone.now() + timezone.timedelta(hours=2),
        status="created"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0011_add_parachutists'),
    ]

    operations = [
        migrations.RunPython(create_training_groups),
    ]
