# Generated by Django 4.2.20 on 2025-05-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0015_add_jump_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumpgroupparachutist',
            name='medical_certified',
        ),
        migrations.RemoveField(
            model_name='jumpgroupparachutist',
            name='practice_passed',
        ),
        migrations.RemoveField(
            model_name='jumpgroupparachutist',
            name='theory_passed',
        ),
        migrations.AddField(
            model_name='jumpgroupparachutist',
            name='medical_checkup_passed',
            field=models.BooleanField(default=False, verbose_name='Медицинское освидетельствование'),
        ),
        migrations.AddField(
            model_name='traininggroupparachutist',
            name='medical_certified',
            field=models.BooleanField(default=False, verbose_name='Мед. сертификация'),
        ),
        migrations.AlterField(
            model_name='jumpgroup',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('Pre-Flight Preparation', 'Предполетная подготовка'), ('Jump In Progress', 'Прыжок в процессе'), ('Completed', 'Завершена'), ('Cancelled', 'Отменена')], default='Created', max_length=50),
        ),
        migrations.AlterField(
            model_name='jumpgroupparachutist',
            name='correct_assignment',
            field=models.BooleanField(default=False, verbose_name='Корректное задание'),
        ),
        migrations.AlterField(
            model_name='jumpgroupparachutist',
            name='equipment_checked',
            field=models.BooleanField(default=False, verbose_name='Снаряжение проверено'),
        ),
        migrations.AlterField(
            model_name='jumpgroupparachutist',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Ожидает'), ('Approved', 'Одобрена'), ('Denied', 'Отклонена')], default='Pending', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='traininggroupparachutist',
            name='parachutist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.parachutist', unique=True),
        ),
    ]
